In [7]:
import pandas as pd
df = pd.read_csv("D:/Python Workbook/BugendaiTech/weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [10]:
df.head
df.shape
row , col = df.shape
row

6

In [13]:
df.tail(2)
df[2:5]
df[:]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [18]:
df.columns
df.day
df['event'] #df.event

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: str

In [20]:
type(df['event'])
df[['event','day','windspeed']]

   event       day  windspeed
0   Rain  1/1/2017          6
1  Sunny  1/2/2017          7
2   Snow  1/3/2017          2
3   Snow  1/4/2017          7
4   Rain  1/5/2017          4
5  Sunny  1/6/2017          2

In [32]:
df['temperature'].min
df.describe()
df[(df.temperature>=32) & (df.windspeed>2)]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [38]:
df[['day','temperature']][df.temperature>=32]
df.loc[0] #returns pandas series
df.head(1)

        day  temperature  windspeed event
0  1/1/2017           32          6  Rain

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          6 non-null      str
 1   temperature  6 non-null      int64
 2   windspeed    6 non-null      int64
 3   event        6 non-null      str
dtypes: int64(2), str(2)
memory usage: 324.0 bytes